name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  filename:
    description: 'The path to HTML or XML document'
    required: true
outputs:
  result:
    description: 'Code coverage percent'
runs:
  using: 'node12'
  main: 'dist/index.js'